### ISSUE TITLE
Add option to insert php code

### ISSUE THREAD

**Issue by hanzei** [cedaro/footer-credits#1]
Hi,

I would be nice if there was an option to insert php code oder html code

**Comment by bradyvercher** [comment]
Hi @Hanzei, evaluating PHP code from user input isn't safe. Is there anything in particular you're looking to add to your credits that you can't add now?

**Comment by hanzei** [comment]
If the editing of wp themes is enable, all users can insert php code. Thus evaluating PHP code is a enabled by deafault in wp.
To answer your question: I want to a the current year in the credits

**Comment by bradyvercher** [comment]
Editing themes in the admin panel requires different capabilities and isn't quite the same concept. Even so, we won't be adding the ability to evaluate PHP in this plugin.

As for displaying the current year, you can do that by inserting `{{year}}` in the field.
